# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target ‘CommonLib_Project’ do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CommonLib_Project
  pod 'Alamofire', '~> 3.4'
  pod 'AlamofireObjectMapper', '~> 3.0'

  target 'CommonLib_ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CommonLib_ProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
